/**
 * Cloudflare Worker that mocks the KV namespace endpoints from Miniflare
 * Generated by Claude based on packages/miniflare/src/workers/kv/namespace.worker.ts
 */

// Constants from KV implementation
const KVLimits = {
  MIN_CACHE_TTL: 60,
  MAX_LIST_KEYS: 1000,
  MAX_KEY_SIZE: 512,
  MAX_VALUE_SIZE: 25 * 1024 * 1024,
  MAX_METADATA_SIZE: 1024,
  MAX_BULK_SIZE: 25 * 1024 * 1024,
};

const KVParams = {
  URL_ENCODED: "urlencoded",
  CACHE_TTL: "cache_ttl",
  EXPIRATION: "expiration",
  EXPIRATION_TTL: "expiration_ttl",
  LIST_LIMIT: "key_count_limit",
  LIST_PREFIX: "prefix",
  LIST_CURSOR: "cursor",
};

const KVHeaders = {
  EXPIRATION: "CF-Expiration",
  METADATA: "CF-KV-Metadata",
};

const MAX_BULK_GET_KEYS = 100;

// In-memory storage for mocking
const kvStore = new Map();

// Utility functions
function decodeKey(key, searchParams) {
  if (searchParams.get(KVParams.URL_ENCODED)?.toLowerCase() !== "true") return key;
  try {
    return decodeURIComponent(key);
  } catch (e) {
    throw new Error("Could not URL-decode key name");
  }
}

function validateKey(key) {
  if (key === "") {
    throw new Error("Key names must not be empty");
  }
  if (key === "." || key === "..") {
    throw new Error(`Illegal key name "${key}". Please use a different name.`);
  }
  const keyLength = new TextEncoder().encode(key).length;
  if (keyLength > KVLimits.MAX_KEY_SIZE) {
    throw new Error(`UTF-8 encoded length of ${keyLength} exceeds key length limit of ${KVLimits.MAX_KEY_SIZE}.`);
  }
}

function validateGetOptions(key, cacheTtl) {
  validateKey(key);
  if (cacheTtl !== undefined && (isNaN(cacheTtl) || cacheTtl < KVLimits.MIN_CACHE_TTL)) {
    throw new Error(`Invalid ${KVParams.CACHE_TTL} of ${cacheTtl}. Cache TTL must be at least ${KVLimits.MIN_CACHE_TTL}.`);
  }
}

function validatePutOptions(key, expiration, expirationTtl, metadata) {
  validateKey(key);

  const now = Math.floor(Date.now() / 1000);
  let validExpiration;

  if (expirationTtl !== null) {
    const ttl = parseInt(expirationTtl);
    if (Number.isNaN(ttl) || ttl <= 0) {
      throw new Error(`Invalid ${KVParams.EXPIRATION_TTL} of ${expirationTtl}. Please specify integer greater than 0.`);
    }
    if (ttl < KVLimits.MIN_CACHE_TTL) {
      throw new Error(`Invalid ${KVParams.EXPIRATION_TTL} of ${expirationTtl}. Expiration TTL must be at least ${KVLimits.MIN_CACHE_TTL}.`);
    }
    validExpiration = now + ttl;
  } else if (expiration !== null) {
    const exp = parseInt(expiration);
    if (Number.isNaN(exp) || exp <= now) {
      throw new Error(`Invalid ${KVParams.EXPIRATION} of ${expiration}. Please specify integer greater than the current number of seconds since the UNIX epoch.`);
    }
    if (exp < now + KVLimits.MIN_CACHE_TTL) {
      throw new Error(`Invalid ${KVParams.EXPIRATION} of ${expiration}. Expiration times must be at least ${KVLimits.MIN_CACHE_TTL} seconds in the future.`);
    }
    validExpiration = exp;
  }

  let validMetadata;
  if (metadata !== null) {
    const metadataLength = new TextEncoder().encode(metadata).length;
    if (metadataLength > KVLimits.MAX_METADATA_SIZE) {
      throw new Error(`Metadata length of ${metadataLength} exceeds limit of ${KVLimits.MAX_METADATA_SIZE}.`);
    }
    validMetadata = JSON.parse(metadata);
  }

  return { expiration: validExpiration, metadata: validMetadata };
}

function validateListOptions(limit, prefix) {
  if (limit !== undefined) {
    if (isNaN(limit) || limit < 1) {
      throw new Error(`Invalid ${KVParams.LIST_LIMIT} of ${limit}. Please specify an integer greater than 0.`);
    }
    if (limit > KVLimits.MAX_LIST_KEYS) {
      throw new Error(`Invalid ${KVParams.LIST_LIMIT} of ${limit}. Please specify an integer less than ${KVLimits.MAX_LIST_KEYS}.`);
    }
  }

  if (prefix != null) {
    const prefixLength = new TextEncoder().encode(prefix).length;
    if (prefixLength > KVLimits.MAX_KEY_SIZE) {
      throw new Error(`UTF-8 encoded length of ${prefixLength} exceeds key length limit of ${KVLimits.MAX_KEY_SIZE}.`);
    }
  }
}

function isExpired(entry) {
  if (!entry.expiration) return false;
  return entry.expiration <= Math.floor(Date.now() / 1000);
}

export default {
  async fetch(request) {
    const url = new URL(request.url);
    const method = request.method;

    try {
      // Route to appropriate handler
      if (method === "GET" && url.pathname === "/") {
        return handleList(url);
      } else if (method === "GET" && url.pathname.startsWith("/")) {
        return handleGet(request, url);
      } else if (method === "POST" && url.pathname === "/bulk/get") {
        return handleBulkGet(request);
      } else if (method === "PUT" && url.pathname.startsWith("/")) {
        return handlePut(request, url);
      } else if (method === "DELETE" && url.pathname.startsWith("/")) {
        return handleDelete(url);
      } else {
        return new Response("Not Found", { status: 404 });
      }
    } catch (error) {
      return new Response(error.message, { status: 400 });
    }
  }
};

// GET /:key - Get a single key
async function handleGet(request, url) {
  const key = decodeKey(url.pathname.substring(1), url.searchParams);
  const cacheTtlParam = url.searchParams.get(KVParams.CACHE_TTL);
  const cacheTtl = cacheTtlParam === null ? undefined : parseInt(cacheTtlParam);

  validateGetOptions(key, cacheTtl);

  const entry = kvStore.get(key);
  if (!entry || isExpired(entry)) {
    if (entry && isExpired(entry)) {
      kvStore.delete(key);
    }
    return new Response("Not Found", { status: 404 });
  }

  const headers = new Headers();
  if (entry.expiration !== undefined) {
    headers.set(KVHeaders.EXPIRATION, entry.expiration.toString());
  }
  if (entry.metadata !== undefined) {
    headers.set(KVHeaders.METADATA, JSON.stringify(entry.metadata));
  }

  return new Response(entry.value, { headers });
}

// POST /bulk/get - Bulk get multiple keys
async function handleBulkGet(request) {
  const body = await request.text();
  const parsedBody = JSON.parse(body);
  const keys = parsedBody.keys;
  const type = parsedBody?.type;

  if (type && type !== "text" && type !== "json") {
    const errorStr = `"${type}" is not a valid type. Use "json" or "text"`;
    return new Response(errorStr, { status: 400 });
  }

  if (keys.length > MAX_BULK_GET_KEYS) {
    const errorStr = `You can request a maximum of ${MAX_BULK_GET_KEYS} keys`;
    return new Response(errorStr, { status: 400 });
  }

  if (keys.length < 1) {
    const errorStr = "You must request a minimum of 1 key";
    return new Response(errorStr, { status: 400 });
  }

  const result = {};
  let totalBytes = 0;

  for (const key of keys) {
    validateGetOptions(key, parsedBody?.cacheTtl);
    const entry = kvStore.get(key);

    if (!entry || isExpired(entry)) {
      if (entry && isExpired(entry)) {
        kvStore.delete(key);
      }
      result[key] = null;
      continue;
    }

    let value = entry.value;
    const size = new TextEncoder().encode(value).length;
    totalBytes += size;

    try {
      if (type === "json" && value) {
        value = JSON.parse(value);
      }
    } catch (err) {
      return new Response(`At least one of the requested keys corresponds to a non-${type} value`, { status: 400 });
    }

    if (parsedBody?.withMetadata && value) {
      result[key] = {
        value: value,
        metadata: entry.metadata ?? null,
      };
    } else {
      result[key] = value;
    }
  }

  if (totalBytes > KVLimits.MAX_BULK_SIZE) {
    return new Response(`Total size of request exceeds the limit of ${KVLimits.MAX_BULK_SIZE / 1024 / 1024}MB`, { status: 413 });
  }

  return new Response(JSON.stringify(result));
}

// PUT /:key - Put a key-value pair
async function handlePut(request, url) {
  const key = decodeKey(url.pathname.substring(1), url.searchParams);
  const rawExpiration = url.searchParams.get(KVParams.EXPIRATION);
  const rawExpirationTtl = url.searchParams.get(KVParams.EXPIRATION_TTL);
  const rawMetadata = request.headers.get(KVHeaders.METADATA);

  const { expiration, metadata } = validatePutOptions(key, rawExpiration, rawExpirationTtl, rawMetadata);

  const contentLength = parseInt(request.headers.get("Content-Length") || "0");
  if (contentLength > KVLimits.MAX_VALUE_SIZE) {
    return new Response(`Value length of ${contentLength} exceeds limit of ${KVLimits.MAX_VALUE_SIZE}.`, { status: 413 });
  }

  const value = await request.text();
  const valueLength = new TextEncoder().encode(value).length;
  if (valueLength > KVLimits.MAX_VALUE_SIZE) {
    return new Response(`Value length of ${valueLength} exceeds limit of ${KVLimits.MAX_VALUE_SIZE}.`, { status: 413 });
  }

  kvStore.set(key, {
    value,
    expiration: expiration ? expiration * 1000 : undefined, // Store as milliseconds
    metadata,
  });

  return new Response();
}

// DELETE /:key - Delete a key
async function handleDelete(url) {
  const key = decodeKey(url.pathname.substring(1), url.searchParams);
  validateKey(key);

  kvStore.delete(key);
  return new Response();
}

// GET / - List keys
async function handleList(url) {
  const limitParam = url.searchParams.get(KVParams.LIST_LIMIT);
  const limit = limitParam === null ? KVLimits.MAX_LIST_KEYS : parseInt(limitParam);
  const prefix = url.searchParams.get(KVParams.LIST_PREFIX) ?? undefined;
  const cursor = url.searchParams.get(KVParams.LIST_CURSOR) ?? undefined;

  validateListOptions(limit, prefix);

  // Get all keys, filter by prefix and cursor
  let keys = Array.from(kvStore.keys());

  if (prefix) {
    keys = keys.filter(key => key.startsWith(prefix));
  }

  if (cursor) {
    keys = keys.filter(key => key > cursor);
  }

  keys.sort();

  // Remove expired entries
  const now = Date.now();
  keys = keys.filter(key => {
    const entry = kvStore.get(key);
    if (entry && entry.expiration && entry.expiration <= now) {
      kvStore.delete(key);
      return false;
    }
    return true;
  });

  // Apply limit
  const hasMore = keys.length > limit;
  const limitedKeys = keys.slice(0, limit);

  const result = {
    keys: limitedKeys.map(key => {
      const entry = kvStore.get(key);
      return {
        name: key,
        expiration: entry?.expiration ? Math.floor(entry.expiration / 1000) : undefined,
        metadata: entry?.metadata ? JSON.stringify(entry.metadata) : undefined,
      };
    }),
    list_complete: !hasMore,
    cacheStatus: null,
  };

  if (hasMore && limitedKeys.length > 0) {
    result.cursor = limitedKeys[limitedKeys.length - 1];
  }

  return Response.json(result);
}
